module.exports = {
  Category: require("./endpoints/category"),
  Game: require("./endpoints/game"),
  Guest: require("./endpoints/guest"),
  Leaderboard: require("./endpoints/leaderboard"),
  Level: require("./endpoints/level"),
  Notification: require("./endpoints/notification"),
  Platform: require("./endpoints/platform"),
  Profile: require("./endpoints/profile"),
  Region: require("./endpoints/region"),
  Run: require("./endpoints/run"),
  Serie: require("./endpoints/serie"),
  User: require("./endpoints/user"),
  Variable: require("./endpoints/variable"),
};
